ALTER TABLE walk_in_summaries
  ADD COLUMN IF NOT EXISTS order_gold        INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS service_customer  INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS scheme_entry      INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS new_scheme        INTEGER NOT NULL DEFAULT 0;
