// Shared incentive master rates and product mapper — used by both the ERP calc page and the KPI dashboard

export interface MasterEntry { code: string; rate: number; minWastage: number }
export interface MapperEntry  { erpName: string; incentiveCode: string }

export const MASTER_RATES: MasterEntry[] = [
  { code: "18K CHAIN",              rate: 3,   minWastage: 15 },
  { code: "K SUNDARI CHAIN",        rate: 3,   minWastage: 5  },
  { code: "KAJUKATLI CHAIN",        rate: 3,   minWastage: 7  },
  { code: "KERALA CHAIN",           rate: 3,   minWastage: 5  },
  { code: "MACHINE CHAIN",          rate: 3,   minWastage: 5  },
  { code: "DELHI CHAIN",            rate: 3,   minWastage: 5  },
  { code: "LOTUS CHAIN",            rate: 3,   minWastage: 5  },
  { code: "FANCY LOTUS CHAIN",      rate: 3,   minWastage: 5  },
  { code: "S LEAF BALLS CHAIN",     rate: 3,   minWastage: 5  },
  { code: "S LEAF CHAIN",           rate: 3,   minWastage: 5  },
  { code: "IPL CHAIN",              rate: 3,   minWastage: 6  },
  { code: "MUGAPPU CHAIN",          rate: 3,   minWastage: 6  },
  { code: "BAAHUBALI CHAIN",        rate: 3,   minWastage: 6  },
  { code: "INDO ITALY CHAIN",       rate: 3,   minWastage: 7  },
  { code: "MILLER CHAIN",           rate: 3,   minWastage: 7  },
  { code: "ITALY CHAIN",            rate: 3,   minWastage: 8  },
  { code: "BACK CHAIN",             rate: 3,   minWastage: 5  },
  { code: "CHOCO CHAIN",            rate: 3,   minWastage: 7  },
  { code: "NAAGINI CHAIN",          rate: 3,   minWastage: 7  },
  { code: "SACHIN TENDULKAR CHAIN", rate: 3,   minWastage: 6  },
  { code: "FANCY BALLS CHAIN",      rate: 3,   minWastage: 8  },
  { code: "FANCY S L CHAIN",        rate: 3,   minWastage: 8  },
  { code: "FANCY CHAIN",            rate: 3,   minWastage: 8  },
  { code: "ROPE CHAIN",             rate: 2,   minWastage: 3  },
  { code: "COINS",                  rate: 0,   minWastage: 0  },
  { code: "BABY BANGLES",           rate: 5,   minWastage: 7  },
  { code: "CBE BANGLES",            rate: 3,   minWastage: 5  },
  { code: "FANCY BANGLES",          rate: 4,   minWastage: 7  },
  { code: "BOMBAY BANGLES",         rate: 4,   minWastage: 7  },
  { code: "ANTIQUE BANGLES",        rate: 7,   minWastage: 9  },
  { code: "STAMPING BRACELET",      rate: 4,   minWastage: 8  },
  { code: "BOMBAY BRACELET",        rate: 4,   minWastage: 8  },
  { code: "LEATHER BRACELET",       rate: 2,   minWastage: 8  },
  { code: "CBE BRACELET",           rate: 5,   minWastage: 6  },
  { code: "BABY BRACELET",          rate: 5,   minWastage: 6  },
  { code: "FANCY BRACELET",         rate: 5,   minWastage: 8  },
  { code: "FANCY KAPPU",            rate: 5,   minWastage: 10 },
  { code: "CASTING BRACELET",       rate: 5,   minWastage: 11 },
  { code: "MUGAPPU DOLLAR",         rate: 8,   minWastage: 11 },
  { code: "FISH DOLLAR",            rate: 8,   minWastage: 10 },
  { code: "CASTING DOLLAR",         rate: 8,   minWastage: 11 },
  { code: "BOMBAY DOLLAR",          rate: 8,   minWastage: 11 },
  { code: "LAKSHMI DOLLAR",         rate: 8,   minWastage: 11 },
  { code: "FANCY DOLLAR",           rate: 8,   minWastage: 9  },
  { code: "KERALA MALAI",           rate: 6,   minWastage: 5  },
  { code: "KASU MALAI",             rate: 6,   minWastage: 7  },
  { code: "CBE MALAI",              rate: 6,   minWastage: 7  },
  { code: "CASTING MALA",           rate: 6,   minWastage: 9  },
  { code: "TURKEY MALAI",           rate: 6,   minWastage: 9  },
  { code: "BOMBAY MALAI",           rate: 5,   minWastage: 9  },
  { code: "FANCY MALAI",            rate: 5,   minWastage: 9  },
  { code: "ANTIQUE MALAI",          rate: 7,   minWastage: 9  },
  { code: "KERALA NECKLACE",        rate: 5,   minWastage: 5  },
  { code: "CBE NECKLACE",           rate: 6,   minWastage: 7  },
  { code: "FANCY NECKLACE",         rate: 5,   minWastage: 9  },
  { code: "TURKEY NECKLACE",        rate: 6,   minWastage: 9  },
  { code: "CASTING NECKLACE",       rate: 6,   minWastage: 9  },
  { code: "BOMBAY NECKLACE",        rate: 6,   minWastage: 9  },
  { code: "BOMBAY CHOKER",          rate: 6,   minWastage: 9  },
  { code: "ANTIQUE NECKLACE",       rate: 7,   minWastage: 9  },
  { code: "ANTIQUE CHOKER",         rate: 7,   minWastage: 9  },
  { code: "BABY RING",              rate: 7,   minWastage: 9  },
  { code: "BOMBAY RING",            rate: 7,   minWastage: 9  },
  { code: "BOLE TV RING",           rate: 7,   minWastage: 6  },
  { code: "CBE RING",               rate: 7,   minWastage: 6  },
  { code: "MAHARAJA RING",          rate: 7,   minWastage: 7  },
  { code: "MALABAR RING",           rate: 7,   minWastage: 8  },
  { code: "WEDDING RING",           rate: 7,   minWastage: 8  },
  { code: "FANCY RING",             rate: 7,   minWastage: 11 },
  { code: "CASTING RING",           rate: 7,   minWastage: 11 },
  { code: "CBE STUD",               rate: 7,   minWastage: 8  },
  { code: "CBE MATTAL",             rate: 7,   minWastage: 8  },
  { code: "BOMBAY MATTAL",          rate: 7,   minWastage: 8  },
  { code: "FANCY MATTAL",           rate: 7,   minWastage: 8  },
  { code: "DELHI MATTAL",           rate: 7,   minWastage: 8  },
  { code: "BABY STUD",              rate: 7,   minWastage: 12 },
  { code: "FANCY JIMIKKI",          rate: 7,   minWastage: 11 },
  { code: "JIMIKKI KAMMAL",         rate: 7,   minWastage: 11 },
  { code: "KERALA STUD",            rate: 7,   minWastage: 11 },
  { code: "NAGMA STUD",             rate: 7,   minWastage: 16 },
  { code: "FANCY STUD",             rate: 7,   minWastage: 11 },
  { code: "ROSE GOLD STUD",         rate: 7,   minWastage: 15 },
  { code: "CASTING STUD",           rate: 7,   minWastage: 11 },
  { code: "BOMBAY STUD",            rate: 7,   minWastage: 11 },
  { code: "KASA STUD",              rate: 7,   minWastage: 9  },
  { code: "TURKEY STUD",            rate: 7,   minWastage: 11 },
  { code: "KUMKI STUD",             rate: 7,   minWastage: 9  },
  { code: "BOMMI STUD",             rate: 7,   minWastage: 9  },
  { code: "STONE STUD",             rate: 7,   minWastage: 16 },
  { code: "ANTIQUE STUD",           rate: 7,   minWastage: 11 },
  { code: "ANTIQUE JIMIKKI",        rate: 7,   minWastage: 11 },
  { code: "THALI",                  rate: 7,   minWastage: 11 },
  { code: "MANI",                   rate: 7,   minWastage: 11 },
  { code: "LAKSHMI KASU",           rate: 7,   minWastage: 11 },
  { code: "MANGA KASU",             rate: 7,   minWastage: 11 },
  { code: "PLAIN THAYATTU",         rate: 7,   minWastage: 11 },
  { code: "ROUND THAYATTU",         rate: 7,   minWastage: 11 },
  { code: "SIDE STUD",              rate: 10,  minWastage: 1  },
  { code: "DIAMOND BESARI",         rate: 100, minWastage: 1  },
  { code: "DIAMOND STUD",           rate: 200, minWastage: 1  },
  { code: "DIAMOND RING",           rate: 200, minWastage: 1  },
  { code: "SB",                     rate: 0,   minWastage: 1  },
  { code: "S",                      rate: 0.5, minWastage: 1  },
  { code: "92.5-S",                 rate: 5,   minWastage: 1  },
  { code: "92.5-L",                 rate: 3,   minWastage: 1  },
  { code: "GOLD KOLUSU",            rate: 3,   minWastage: 7  },
];

export const PRODUCT_MAPPER: MapperEntry[] = [
  { erpName: "FANCY BANGLES",           incentiveCode: "FANCY BANGLES"      },
  { erpName: "BOMBAY BANGLES",          incentiveCode: "BOMBAY BANGLES"     },
  { erpName: "BABY BANGLES",            incentiveCode: "BABY BANGLES"       },
  { erpName: "ANTIQUE BANGLES",         incentiveCode: "ANTIQUE BANGLES"    },
  { erpName: "CBE BANGLES",             incentiveCode: "CBE BANGLES"        },
  { erpName: "VALAIYAM",                incentiveCode: "FANCY BANGLES"      },
  { erpName: "FANCY KAPPU",             incentiveCode: "FANCY KAPPU"        },
  { erpName: "BAAHUBALI CHAIN",         incentiveCode: "BAAHUBALI CHAIN"    },
  { erpName: "FANCY BAAHUBALI CHAIN",   incentiveCode: "BAAHUBALI CHAIN"    },
  { erpName: "BACK CHAIN",              incentiveCode: "BACK CHAIN"         },
  { erpName: "CHOCO CHAIN",             incentiveCode: "CHOCO CHAIN"        },
  { erpName: "DELHI CHAIN",             incentiveCode: "DELHI CHAIN"        },
  { erpName: "FANCY BALLS CHAIN",       incentiveCode: "FANCY BALLS CHAIN"  },
  { erpName: "FANCY CHAIN",             incentiveCode: "FANCY CHAIN"        },
  { erpName: "FANCY S L CHAIN",         incentiveCode: "FANCY S L CHAIN"    },
  { erpName: "INDO ITALY CHAIN",        incentiveCode: "INDO ITALY CHAIN"   },
  { erpName: "ITALY CHAIN",             incentiveCode: "ITALY CHAIN"        },
  { erpName: "K SUNDARI CHAIN",         incentiveCode: "K SUNDARI CHAIN"    },
  { erpName: "SUNDRI CHAIN",            incentiveCode: "K SUNDARI CHAIN"    },
  { erpName: "KAJUKATLI CHAIN",         incentiveCode: "KAJUKATLI CHAIN"    },
  { erpName: "LOTUS CHAIN",             incentiveCode: "LOTUS CHAIN"        },
  { erpName: "MACHINE CHAIN",           incentiveCode: "MACHINE CHAIN"      },
  { erpName: "MUGAPPU CHAIN",           incentiveCode: "MUGAPPU CHAIN"      },
  { erpName: "ROPE CHAIN",              incentiveCode: "ROPE CHAIN"         },
  { erpName: "S LEAF CHAIN",            incentiveCode: "S LEAF CHAIN"       },
  { erpName: "S LEAF BALLS CHAIN",      incentiveCode: "S LEAF BALLS CHAIN" },
  { erpName: "SACHIN TENDULKAR CHAIN",  incentiveCode: "SACHIN TENDULKAR CHAIN" },
  { erpName: "NAAGINI CHAIN",           incentiveCode: "NAAGINI CHAIN"      },
  { erpName: "KERALA CHAIN",            incentiveCode: "KERALA CHAIN"       },
  { erpName: "MILLER CHAIN",            incentiveCode: "MILLER CHAIN"       },
  { erpName: "IPL CHAIN",               incentiveCode: "IPL CHAIN"          },
  { erpName: "18K CHAIN",               incentiveCode: "18K CHAIN"          },
  { erpName: "CHAIN",                   incentiveCode: "S"                  },
  { erpName: "CASTING BRACELET",        incentiveCode: "CASTING BRACELET"   },
  { erpName: "BABY BRACELET",           incentiveCode: "BABY BRACELET"      },
  { erpName: "BOMBAY BRACELET",         incentiveCode: "BOMBAY BRACELET"    },
  { erpName: "CBE BRACELET",            incentiveCode: "CBE BRACELET"       },
  { erpName: "LEATHER BRACELET",        incentiveCode: "LEATHER BRACELET"   },
  { erpName: "STAMPING BRACELET",       incentiveCode: "STAMPING BRACELET"  },
  { erpName: "FANCY BRACELET",          incentiveCode: "FANCY BRACELET"     },
  { erpName: "CUBAN BRACELET",          incentiveCode: "CASTING BRACELET"   },
  { erpName: "BRACELET",                incentiveCode: "S"                  },
  { erpName: "CBE RING",                incentiveCode: "CBE RING"           },
  { erpName: "CASTING RING",            incentiveCode: "CASTING RING"       },
  { erpName: "BABY RING",               incentiveCode: "BABY RING"          },
  { erpName: "BOMBAY RING",             incentiveCode: "BOMBAY RING"        },
  { erpName: "MAHARAJA RING",           incentiveCode: "MAHARAJA RING"      },
  { erpName: "WEDDING RING",            incentiveCode: "WEDDING RING"       },
  { erpName: "BOLE TV RING",            incentiveCode: "BOLE TV RING"       },
  { erpName: "FANCY RING",              incentiveCode: "FANCY RING"         },
  { erpName: "MALABAR RING",            incentiveCode: "MALABAR RING"       },
  { erpName: "CASTING STUD",            incentiveCode: "CASTING STUD"       },
  { erpName: "CBE STUD",                incentiveCode: "CBE STUD"           },
  { erpName: "BABY STUD",               incentiveCode: "BABY STUD"          },
  { erpName: "BOMBAY STUD",             incentiveCode: "BOMBAY STUD"        },
  { erpName: "FANCY STUD",              incentiveCode: "FANCY STUD"         },
  { erpName: "KUMKI STUD",              incentiveCode: "KUMKI STUD"         },
  { erpName: "KASA STUD",               incentiveCode: "KASA STUD"          },
  { erpName: "BOMMI STUD",              incentiveCode: "BOMMI STUD"         },
  { erpName: "SIDE STUD",               incentiveCode: "SIDE STUD"          },
  { erpName: "75K SIDE STUD",           incentiveCode: "SIDE STUD"          },
  { erpName: "FANCY JIMIKKI",           incentiveCode: "FANCY JIMIKKI"      },
  { erpName: "JIMIKKI KAMMAL",          incentiveCode: "JIMIKKI KAMMAL"     },
  { erpName: "JIMMIKI",                 incentiveCode: "JIMIKKI KAMMAL"     },
  { erpName: "DELHI MATTAL",            incentiveCode: "DELHI MATTAL"       },
  { erpName: "BOMBAY MATTAL",           incentiveCode: "BOMBAY MATTAL"      },
  { erpName: "FANCY MATTAL",            incentiveCode: "FANCY MATTAL"       },
  { erpName: "CBE MATTAL",              incentiveCode: "CBE MATTAL"         },
  { erpName: "TITANIC MATTAL",          incentiveCode: "BOMBAY MATTAL"      },
  { erpName: "NAGMA STUD",              incentiveCode: "NAGMA STUD"         },
  { erpName: "KERALA STUD",             incentiveCode: "KERALA STUD"        },
  { erpName: "TURKEY STUD",             incentiveCode: "TURKEY STUD"        },
  { erpName: "ROSE GOLD STUD",          incentiveCode: "ROSE GOLD STUD"     },
  { erpName: "STONE STUD",              incentiveCode: "STONE STUD"         },
  { erpName: "ANTIQUE STUD",            incentiveCode: "ANTIQUE STUD"       },
  { erpName: "ANTIQUE JIMIKKI",         incentiveCode: "ANTIQUE JIMIKKI"    },
  { erpName: "CBE MALAI",               incentiveCode: "CBE MALAI"          },
  { erpName: "BOMBAY MALAI",            incentiveCode: "BOMBAY MALAI"       },
  { erpName: "FANCY MALAI",             incentiveCode: "FANCY MALAI"        },
  { erpName: "ANTIQUE MALAI",           incentiveCode: "ANTIQUE MALAI"      },
  { erpName: "ANTIQUE LAKSHMI MALAI",   incentiveCode: "ANTIQUE MALAI"      },
  { erpName: "KERALA MALAI",            incentiveCode: "KERALA MALAI"       },
  { erpName: "LAKSHMI MALAI",           incentiveCode: "KERALA MALAI"       },
  { erpName: "KASU MALAI",              incentiveCode: "KASU MALAI"         },
  { erpName: "TURKEY MALAI",            incentiveCode: "TURKEY MALAI"       },
  { erpName: "CASTING MALA",            incentiveCode: "CASTING MALA"       },
  { erpName: "ANTIQUE NECKLACE",        incentiveCode: "ANTIQUE NECKLACE"   },
  { erpName: "BOMBAY NECKLACE",         incentiveCode: "BOMBAY NECKLACE"    },
  { erpName: "CBE NECKLACE",            incentiveCode: "CBE NECKLACE"       },
  { erpName: "CASTING NECKLACE",        incentiveCode: "CASTING NECKLACE"   },
  { erpName: "FANCY NECKLACE",          incentiveCode: "FANCY NECKLACE"     },
  { erpName: "TURKEY NECKLACE",         incentiveCode: "TURKEY NECKLACE"    },
  { erpName: "KERALA NECKLACE",         incentiveCode: "KERALA NECKLACE"    },
  { erpName: "ANTIQUE CHOKER",          incentiveCode: "ANTIQUE CHOKER"     },
  { erpName: "BOMBAY CHOKER",           incentiveCode: "BOMBAY CHOKER"      },
  { erpName: "CASTING DOLLAR",          incentiveCode: "CASTING DOLLAR"     },
  { erpName: "FANCY DOLLAR",            incentiveCode: "FANCY DOLLAR"       },
  { erpName: "FISH DOLLAR",             incentiveCode: "FISH DOLLAR"        },
  { erpName: "BOMBAY DOLLAR",           incentiveCode: "BOMBAY DOLLAR"      },
  { erpName: "ROSE DOLLAR",             incentiveCode: "FANCY DOLLAR"       },
  { erpName: "LAKSHMI DOLLAR",          incentiveCode: "LAKSHMI DOLLAR"     },
  { erpName: "MUGAPPU DOLLAR",          incentiveCode: "MUGAPPU DOLLAR"     },
  { erpName: "THALI",                   incentiveCode: "THALI"              },
  { erpName: "MANI",                    incentiveCode: "MANI"               },
  { erpName: "LAKSHMI KASU",            incentiveCode: "LAKSHMI KASU"       },
  { erpName: "MANGA KASU",              incentiveCode: "MANGA KASU"         },
  { erpName: "PLAIN THAYATTU",          incentiveCode: "PLAIN THAYATTU"     },
  { erpName: "ROUND THAYATTU",          incentiveCode: "ROUND THAYATTU"     },
  { erpName: "DIAMOND BESARI",          incentiveCode: "DIAMOND BESARI"     },
  { erpName: "DIAMOND STUD",            incentiveCode: "DIAMOND STUD"       },
  { erpName: "DIAMOND RING",            incentiveCode: "DIAMOND RING"       },
  { erpName: "COINS",                   incentiveCode: "COINS"              },
  { erpName: "PURE GOLD",               incentiveCode: "COINS"              },
  { erpName: "PEARL STONE",             incentiveCode: "COINS"              },
  { erpName: "SILVER COIN",             incentiveCode: "SB"                 },
  { erpName: "PURE SILVER",             incentiveCode: "SB"                 },
  { erpName: "S",                       incentiveCode: "S"                  },
  { erpName: "SILVER CHAIN",            incentiveCode: "S"                  },
  { erpName: "SILVER METTI",            incentiveCode: "S"                  },
  { erpName: "SILVER KODI",             incentiveCode: "S"                  },
  { erpName: "SILVER OMT",              incentiveCode: "S"                  },
  { erpName: "SILVER KADA",             incentiveCode: "S"                  },
  { erpName: "SILVER THANDAI",          incentiveCode: "S"                  },
  { erpName: "NAKASU THANDAI",          incentiveCode: "S"                  },
  { erpName: "SILVER WATCH",            incentiveCode: "S"                  },
  { erpName: "KUTHU VILAKKU",           incentiveCode: "S"                  },
  { erpName: "AGAL VILAKU",             incentiveCode: "S"                  },
  { erpName: "PAVALA MANI",             incentiveCode: "S"                  },
  { erpName: "BANGLE",                  incentiveCode: "S"                  },
  { erpName: "SILVER BANGLE",           incentiveCode: "S"                  },
  { erpName: "BOMBAY KOLUSU-K",         incentiveCode: "S"                  },
  { erpName: "BOMBAY KOLUSU-S",         incentiveCode: "S"                  },
  { erpName: "K-KOTHU",                 incentiveCode: "S"                  },
  { erpName: "K-MOGAPU",               incentiveCode: "S"                  },
  { erpName: "A-MOGAPU KOLUSU",         incentiveCode: "S"                  },
  { erpName: "A-KOTHU KOLUSU",          incentiveCode: "S"                  },
  { erpName: "UIREY KOLUSU",            incentiveCode: "S"                  },
  { erpName: "K-SALANGAI 1",            incentiveCode: "S"                  },
  { erpName: "92.5-S",                  incentiveCode: "92.5-S"             },
  { erpName: "92.5-L",                  incentiveCode: "92.5-L"             },
  { erpName: "92.5 CHAIN",              incentiveCode: "92.5-S"             },
  { erpName: "92.5 BRACELET",           incentiveCode: "92.5-S"             },
  { erpName: "92.5 SILVER RING",        incentiveCode: "92.5-S"             },
  { erpName: "92.5 DOLLAR",             incentiveCode: "92.5-S"             },
  { erpName: "92.5 BANGLE",             incentiveCode: "92.5-S"             },
  { erpName: "92.5 KAPPU",              incentiveCode: "92.5-S"             },
  { erpName: "92.5 STUD",               incentiveCode: "S"                  },
  { erpName: "92.5 TEMPLE JEWEL",       incentiveCode: "92.5-S"             },
  { erpName: "92.5 SILVER OMT",         incentiveCode: "92.5-S"             },
  { erpName: "ANTIQUE METTI",           incentiveCode: "92.5-S"             },
  { erpName: "CASTING METTI",           incentiveCode: "92.5-S"             },
  { erpName: "IDOL",                    incentiveCode: "92.5-S"             },
  { erpName: "GOLD KOLUSU",             incentiveCode: "GOLD KOLUSU"        },
  { erpName: "SB",                      incentiveCode: "SB"                 },
];

// Returns incentive for one sale item, from one salesperson's perspective.
// share: 1.0 if sole SP, 0.7 if SP1 with a partner, 0.3 if SP2
export function calcItemIncentive(
  description: string,
  vaPct: number,
  netWt: number,
  share: number,
): number {
  const key = description.trim().toUpperCase();
  const mapEntry = PRODUCT_MAPPER.find(m => m.erpName === key);
  let code = (mapEntry?.incentiveCode ?? key).toUpperCase();
  if (code === "92.5-S" && netWt >= 20) code = "92.5-L";
  const master = MASTER_RATES.find(m => m.code === code);
  if (!master || master.rate <= 0) return 0;
  if (vaPct < master.minWastage) return 0;
  return parseFloat((master.rate * netWt * share).toFixed(2));
}
